In [ ]:
#primero obtendre informacion sobre consumo de energia electrica en el mundo (https://datos.enerdata.net/)

In [1]:
!pip install jupyter-dash

Collecting jupyter-dash
  Downloading jupyter_dash-0.4.2-py3-none-any.whl.metadata (3.6 kB)
Collecting dash (from jupyter-dash)
  Downloading dash-2.18.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from jupyter-dash) (2.32.3)
Requirement already satisfied: flask in /usr/local/lib/python3.10/dist-packages (from jupyter-dash) (2.2.5)
Collecting retrying (from jupyter-dash)
  Downloading retrying-1.3.4-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from jupyter-dash) (7.34.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.10/dist-packages (from jupyter-dash) (5.5.6)
Collecting ansi2html (from jupyter-dash)
  Downloading ansi2html-1.9.2-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from jupyter-dash) (1.6.0)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.10/dist-packages (from dash->jupyter-dash) (3.0.4)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from dash->jupyter-dash) (5.15.0)
Collecting dash-html-components==2.0.0 (from dash->jupyter-dash)
  Downloading dash_html_components-2.0.0-py3-none-any.whl.metadata (3.8 kB)
Collecting dash-core-components==2.0.0 (from dash->jupyter-dash)
  Downloading dash_core_components-2.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting dash-table==5.0.0 (from dash->jupyter-dash)
  Downloading dash_table-5.0.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from dash->jupyter-dash) (8.4.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from dash->jupyter-dash) (4.12.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from dash->jupyter-dash) (71.0.4)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from flask->jupyter-dash) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from flask->jupyter-dash) (2.2.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from flask->jupyter-dash) (8.1.7)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter-dash) (0.2.0)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter-dash) (5.7.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter-dash) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter-dash) (6.3.3)
Collecting jedi>=0.16 (from ipython->jupyter-dash)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (3.0.47)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->jupyter-dash) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->jupyter-dash) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->jupyter-dash) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->jupyter-dash) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->jupyter-dash) (2024.8.30)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from retrying->jupyter-dash) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->jupyter-dash) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->flask->jupyter-dash) (2.1.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->jupyter-dash) (0.7.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=5.0.0->dash->jupyter-dash) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=5.0.0->dash->jupyter-dash) (24.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter-dash) (0.2.13)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->dash->jupyter-dash) (3.20.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-client->ipykernel->jupyter-dash) (5.7.2)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.10/dist-packages (from jupyter-client->ipykernel->jupyter-dash) (24.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.10/dist-packages (from jupyter-client->ipykernel->jupyter-dash) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.0->jupyter-client->ipykernel->jupyter-dash) (4.2.2)
Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Downloading ansi2html-1.9.2-py3-none-any.whl (17 kB)
Downloading dash-2.18.0-py3-none-any.whl (7.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 50.1 MB/s eta 0:00:00
Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Installing collected packages: dash-table, dash-html-components, dash-core-components, retrying, jedi, ansi2html, dash, jupyter-dash
Successfully installed ansi2html-1.9.2 dash-2.18.0 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 jedi-0.19.1 jupyter-dash-0.4.2 retrying-1.3.4

## importar las diferentes librerias que se necesiten

In [2]:
import plotly.express as px
import pandas as pd
import numpy as np
from shapely.geometry import Point
from google.colab import drive

## aqui doy acceso a mi drive donde tengo el data set de energia electrica

In [3]:
#montando el drive para acceder a la data guardada en el mismo
drive.mount('/content/drive')
# Ruta al archivo
archivo_xlsx = '/content/drive/My Drive/enerda/Enerdata.xlsx'

Mounted at /content/drive

In [ ]:
# para cuando se usa el archivo sin el drive
#archivo_xlsx = 'Enerdata.xlsx'

### una vez montado el drive extraigo una hoja especifica del excel de mi interes y la convierto en un dataframe

In [4]:
# obtener la hoja de consumo mundial de energia electrica
# establecer que los encabezados estan situados en la quinta fila
df_enerdata_c = pd.read_excel(archivo_xlsx, sheet_name='Total energy consumption', header=5)
# quitar las columnas y filas ubicadas en extremos y que no se usaran
Total_energy_consumption=df_enerdata_c.iloc[:-4, 1:-2]
# darle un nombre a la primera columna para su identificacion facil
Total_energy_consumption.rename(columns={'Unnamed: 1': 'Paises'}, inplace=True)

# Mostrar las primeras filas del DataFrame
Total_energy_consumption.head()

,Paises,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,World,8675.688505,8785.603489,8796.356709,8885.485474,8951.808402,9160.182053,9424.074155,9503.081144,9515.754008,...,13736.014788,13779.505117,13916.934077,14211.919309,14562.636106,14782.989319,14237.157508,14985.888928,15102.208734,15435.801486
1,OECD,4592.822778,4646.888699,4688.831151,4751.926118,4840.056843,4936.423538,5090.090515,5134.372250,5153.799243,...,5357.322804,5349.675197,5367.369785,5406.921324,5458.042759,5430.834743,5069.292441,5308.917700,5245.519455,5165.954786
2,G7,3495.572033,3535.307642,3577.038167,3620.641165,3685.349747,3750.088683,3846.260555,3861.217400,3878.964564,...,3827.802443,3804.998538,3782.322800,3789.691039,3837.688686,3811.831310,3520.607406,3688.512262,3650.688725,3599.027653
3,BRICS,2162.217145,2202.145679,2164.819659,2181.577081,2158.342633,2226.164009,2296.399054,2289.842115,2241.007898,...,5066.028277,5048.042966,5061.061566,5244.826602,5477.044351,5598.237701,5638.962760,6026.811681,6178.142301,6495.671060
4,Europe,1792.642559,1786.861316,1743.877642,1738.910926,1731.558081,1781.615177,1850.243352,1836.047639,1851.048330,...,1792.178220,1816.062639,1838.495294,1872.024518,1857.560150,1831.158239,1714.978439,1811.423616,1716.760421,1650.587547

## creare un pequeño codigo que recopile los datos de los paises miembros del brics sin rusia por que no lo tengo y lo reste a el total de los brics

In [5]:
#agregar los datos de rusia restandole a brics los demas paises miembros
paises_brics=['Brazil','India','China','South Africa']

#iniciar el primer dato de rusia
reg2_rusia={'Paises':'Rusia'}

# un for basandome en los años que necesito
for i in range(1990,2024):
  sum_año = 0
  # un segundo for para pasar de pais en pais
  for j in paises_brics:
    v_actual = Total_energy_consumption.loc[Total_energy_consumption['Paises'] == j , i ].values[0]
    sum_año +=v_actual
  #una vez obtenido la suma total de un año de los diferentes paises restarlo a los brics
  v_rusia = Total_energy_consumption.loc[Total_energy_consumption['Paises'] == 'BRICS' , i ].values[0] - sum_año
  #agregar el dato de rusia al diccionario
  reg2_rusia[i] = v_rusia

#imprimir el diccionario para comprobacion
print(reg2_rusia)

#agregar el diccionario a el dataset
Total_energy_consumption.loc[len(Total_energy_consumption)] = reg2_rusia

#confirmar que ya esta en el data set
Total_energy_consumption.head()

{'Paises': 'Rusia', 1990: 888.7267875500402, 1991: 879.5076168589103, 1992: 805.1112985944812, 1993: 760.4690619698797, 1994: 663.24284131165, 1995: 641.9153787320201, 1996: 637.4612892651701, 1997: 609.2564698782601, 1998: 594.5675403601404, 1999: 611.5506908592299, 2000: 621.9381192560197, 2001: 629.4219808589401, 2002: 626.6049508811802, 2003: 648.3114964813303, 2004: 650.5633448243302, 2005: 655.4374730182203, 2006: 675.0903845281996, 2007: 677.2438443265701, 2008: 694.90369443081, 2009: 652.2245303013201, 2010: 695.1623948012107, 2011: 717.1011865707601, 2012: 737.0465933166097, 2013: 721.1616136387802, 2014: 713.9648357187298, 2015: 700.32371519135, 2016: 715.85682909548, 2017: 741.2193047990104, 2018: 801.8536044186603, 2019: 763.1629133163297, 2020: 759.3011801491002, 2021: 838.3617483524804, 2022: 836.3149124925203, 2023: 838.4198472010803}

,Paises,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,World,8675.688505,8785.603489,8796.356709,8885.485474,8951.808402,9160.182053,9424.074155,9503.081144,9515.754008,...,13736.014788,13779.505117,13916.934077,14211.919309,14562.636106,14782.989319,14237.157508,14985.888928,15102.208734,15435.801486
1,OECD,4592.822778,4646.888699,4688.831151,4751.926118,4840.056843,4936.423538,5090.090515,5134.372250,5153.799243,...,5357.322804,5349.675197,5367.369785,5406.921324,5458.042759,5430.834743,5069.292441,5308.917700,5245.519455,5165.954786
2,G7,3495.572033,3535.307642,3577.038167,3620.641165,3685.349747,3750.088683,3846.260555,3861.217400,3878.964564,...,3827.802443,3804.998538,3782.322800,3789.691039,3837.688686,3811.831310,3520.607406,3688.512262,3650.688725,3599.027653
3,BRICS,2162.217145,2202.145679,2164.819659,2181.577081,2158.342633,2226.164009,2296.399054,2289.842115,2241.007898,...,5066.028277,5048.042966,5061.061566,5244.826602,5477.044351,5598.237701,5638.962760,6026.811681,6178.142301,6495.671060
4,Europe,1792.642559,1786.861316,1743.877642,1738.910926,1731.558081,1781.615177,1850.243352,1836.047639,1851.048330,...,1792.178220,1816.062639,1838.495294,1872.024518,1857.560150,1831.158239,1714.978439,1811.423616,1716.760421,1650.587547

## Obteniendo datos de geometria de los paises

In [6]:
# carga la data de la geometria de los paises
prueba = px.data.gapminder()
prueba2 = prueba.loc[prueba.groupby('country')['year'].idxmax()]
prueba2.drop(['year','lifeExp','pop','gdpPercap'], axis = 1, inplace= True)
reg_rusia = {'country': 'Rusia', 'continent': 'Europe', 'iso_alpha': 'RUS', 'iso_num': 643}
prueba2.loc[len(prueba2)] = reg_rusia
prueba2.head()

        country continent iso_alpha  iso_num
11  Afghanistan      Asia       AFG        4
23      Albania    Europe       ALB        8
35      Algeria    Africa       DZA       12
47       Angola    Africa       AGO       24
59    Argentina  Americas       ARG       32

## pequeño analisis para determinar cual dataset es mas completo

In [7]:
paises_df1 = set(Total_energy_consumption['Paises'])
paises_df2 = set(prueba2['country'])

energy_consumption_mundial = paises_df1 - paises_df2  # Países en df1 pero no en df2
geopandas_world = paises_df2 - paises_df1  # Países en df2 pero no en df1
# Convertir a listas
paises_unicos_df1 = list(energy_consumption_mundial)
paises_unicos_df2 = list(geopandas_world)
#acomodar las listas en orden alfabetico
paises_unicos_df1.sort()
paises_unicos_df2.sort()
print("Países únicos en energy_consumption_mundial que no están en geopandas_world:", len(paises_unicos_df1))
print("Países únicos en geopandas_world que no están en energy_consumption_mundial:", len(paises_unicos_df2))

Países únicos en energy_consumption_mundial que no están en geopandas_world: 22
Países únicos en geopandas_world que no están en energy_consumption_mundial: 104

## debido al anterior analisis se conbinan ambos dataset pero se establece como principal el de gapminder

In [8]:

#combinando con el data set de produccion de energia electrica
cons_combinado = pd.merge(Total_energy_consumption, prueba2, left_on='Paises', right_on='country', how='right')

# eliminar la primera columna 'paises' (para luego reemplazarla con la columna 'name' )
cons_combinado.drop('Paises', axis=1, inplace=True)

# mover la columna 'country' a la primera posicion para una mejor comprension
cons_combinado = cons_combinado[['country'] + [col for col in cons_combinado.columns if col != 'country']]

# cambiar el nombre de la columna 'name' por 'Paises'
cons_combinado.rename(columns={'country': 'Paises'}, inplace=True)

# mostrar las primeras filas del resultado
cons_combinado

,Paises,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2017,2018,2019,2020,2021,2022,2023,continent,iso_alpha,iso_num
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia,AFG,4
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe,ALB,8
2,Algeria,21.166734,23.165670,24.170773,26.026684,27.025515,25.903467,25.503388,26.959643,28.945128,...,55.519999,58.861425,61.257735,57.149546,61.826642,65.251608,70.275462,Africa,DZA,12
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,AGO,24
4,Argentina,45.397065,47.970527,49.708000,48.453308,49.947002,53.028659,55.913305,58.461865,59.757361,...,80.981441,78.491272,78.568691,73.143772,81.386108,81.152129,79.874104,Americas,ARG,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia,PSE,275
139,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Asia,YEM,887
140,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,ZMB,894
141,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,ZWE,716
142,Rusia,888.726788,879.507617,805.111299,760.469062,663.242841,641.915379,637.461289,609.256470,594.567540,...,741.219305,801.853604,763.162913,759.301180,838.361748,836.314912,838.419847,Europe,RUS,643

## una vez obtenido el dataset sobre el que voy a trabajar hago un analisis de los datos

### en este caso verifico los nulos en las columnas

In [9]:
cons_combinado.isnull().sum()

Paises         0
1990         104
1991         104
1992         104
1993         104
1994         104
1995         104
1996         104
1997         104
1998         104
1999         104
2000         104
2001         104
2002         104
2003         104
2004         104
2005         104
2006         104
2007         104
2008         104
2009         104
2010         104
2011         104
2012         104
2013         104
2014         104
2015         104
2016         104
2017         104
2018         104
2019         104
2020         104
2021         104
2022         104
2023         104
continent      0
iso_alpha      0
iso_num        0
dtype: int64

### aqui verifico que los tipos de datos sean los correctos

In [10]:
cons_combinado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 38 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Paises     143 non-null    object
 1   1990       39 non-null     float64
 2   1991       39 non-null     float64
 3   1992       39 non-null     float64
 4   1993       39 non-null     float64
 5   1994       39 non-null     float64
 6   1995       39 non-null     float64
 7   1996       39 non-null     float64
 8   1997       39 non-null     float64
 9   1998       39 non-null     float64
 10  1999       39 non-null     float64
 11  2000       39 non-null     float64
 12  2001       39 non-null     float64
 13  2002       39 non-null     float64
 14  2003       39 non-null     float64
 15  2004       39 non-null     float64
 16  2005       39 non-null     float64
 17  2006       39 non-null     float64
 18  2007       39 non-null     float64
 19  2008       39 non-null     float64
 20  2009       39 non-null     float64
 21  2010       39 non-null     float64
 22  2011       39 non-null     float64
 23  2012       39 non-null     float64
 24  2013       39 non-null     float64
 25  2014       39 non-null     float64
 26  2015       39 non-null     float64
 27  2016       39 non-null     float64
 28  2017       39 non-null     float64
 29  2018       39 non-null     float64
 30  2019       39 non-null     float64
 31  2020       39 non-null     float64
 32  2021       39 non-null     float64
 33  2022       39 non-null     float64
 34  2023       39 non-null     float64
 35  continent  143 non-null    object
 36  iso_alpha  143 non-null    object
 37  iso_num    143 non-null    int64
dtypes: float64(34), int64(1), object(3)
memory usage: 42.6+ KB

### aqui compruebo datos de medicion central por si los necesito mas adelante

In [11]:
cons_combinado.describe()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,iso_num
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,...,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,143.000000
mean,178.521822,181.677002,182.908463,185.894387,187.836332,192.479968,198.187173,199.415953,199.300514,204.398248,...,289.545843,291.510504,296.855310,305.367790,310.443358,301.325288,317.506599,322.398312,329.255883,427.398601
std,341.406637,344.351092,346.908534,351.150359,355.318332,361.387426,370.622781,371.988589,370.842132,380.970431,...,582.810918,577.925855,592.262283,617.191378,634.019283,634.057861,673.342618,688.715802,724.506291,248.895960
min,13.776363,5.365732,11.168121,15.490717,15.473137,15.491357,15.898612,16.364121,16.233644,17.415451,...,16.184752,16.550090,16.699226,16.633717,16.030834,15.364187,16.165333,15.496544,15.119591,4.000000
25%,23.861867,25.729704,27.016366,29.981392,31.359879,34.175009,34.280927,37.052436,36.112261,33.088809,...,48.327143,50.483031,52.075257,51.562240,51.745411,47.286556,51.370512,47.818220,46.288194,211.000000
50%,67.195620,71.430769,74.213783,75.516123,73.579687,74.901575,77.951185,81.095302,82.091986,84.856179,...,117.681653,118.399352,124.126017,123.724964,120.175864,115.948477,119.763311,115.289215,118.123088,410.000000
75%,146.767824,150.345923,150.616560,152.311779,155.873136,164.387965,168.679395,175.031141,179.532447,183.123058,...,245.426035,247.233785,247.112971,250.055950,265.806109,248.800655,252.324753,275.706252,262.565119,640.000000
max,1911.016994,1928.652956,1966.416214,1999.339908,2039.288619,2064.038185,2113.582190,2134.838507,2150.370626,2205.753890,...,3034.323122,3005.298238,3112.928690,3253.080392,3395.561886,3499.707607,3719.264730,3808.522517,4059.945349,894.000000

## ya con los datos preparados implemento un grafico en DASH que contenga una vista de los paises sobre un mapa mundial y que su tasa de consumo basada en un año se muestre dependiendo de un slider en la parte superior ademas que los paises que mas consumen mostrandose a la derecha

In [12]:
import dash
import pandas as pd
import numpy as np
from dash import dcc
from dash import html
import plotly.express as px
import plotly.graph_objs as go

# Crear la aplicación Dash
app = dash.Dash(__name__)

# Datos para el mapa mundi
data = cons_combinado.copy()

# lista de paises para el drop down
resul_p = list(set(data['Paises']) - set(paises_unicos_df2))
resul_p.sort()


# Layout de la aplicación
app.layout = html.Div([
    html.H1("Mapa Mundi Interactivo"),

    html.Div([
        dcc.Graph(id='mapa-mundi')
    ], style={'width': '59%', 'display': 'inline-block'}),

    html.Div([dcc.Graph(id='bar-group')
    ], style={'width': '39%', 'display': 'inline-block'}),

    html.Div([html.Label("Año:"),
        ], style={'width': '100%', 'display': 'inline-block'}),

    html.Div([dcc.Slider(id='year-slider', min=1990, max=2023,
                  value=2012,  # Año inicial
                  marks={str(year): str(year) for year in range(1990, 2024)},
                  step=None ),]),
    html.Div([
        dcc.Graph(id='line-country')
        ]),

    html.Div([
        html.Div([
            "año que desea predecir: ",
            dcc.Input(id='fanio-input', value=2020, type='number')
        ], style={'width': '30%', 'display': 'inline-block', 'text-align': 'center'}),

        html.Div([
            dcc.Dropdown(
                id='pais-dropdown',
                options=[{'label': pais, 'value': pais} for pais in resul_p],
                value=resul_p[0]  # Valor inicial del dropdown
            ),
        ], style={'width': '30%', 'display': 'inline-block', 'text-align': 'center'})
    ], style={'display': 'flex', 'justify-content': 'center', 'align-items': 'center'}),

    html.Div([dcc.Graph(
        id='modelo-graph')
    ]),

],style={'background':'white'})

@app.callback(
    dash.dependencies.Output('mapa-mundi', 'figure'),
    dash.dependencies.Output('bar-group', 'figure'),
    dash.dependencies.Output('line-country', 'figure'),
    dash.dependencies.Output('modelo-graph', 'figure'),
    [dash.dependencies.Input('year-slider', 'value'),
     dash.dependencies.Input('pais-dropdown', 'value'),
     dash.dependencies.Input('fanio-input', 'value')]
)

def update_map(selected_year, selected_pais, selected_fanio):
  #capturando los datos que se van a mostrar
  year = selected_year
  pais = selected_pais


  try:
    f_year = int(selected_fanio)
  except ValueError:
    f_year = 2020

  try:
    data_ord = data.sort_values(by=year, ascending=False)
    #armando el grafico principal del mapa mundi
    fig = px.choropleth(data_ord,
                          locations="iso_alpha",
                          color='Paises',
                          hover_name=year,
                          color_discrete_sequence=px.colors.qualitative.Prism,
                          title=f'consumo de energia en {year} por paises')
    fig.update_layout(
          showlegend=False,
          xaxis=dict(fixedrange=True),  # Bloquear zoom en el eje x
          yaxis=dict(fixedrange=True),  # Bloquear zoom en el eje y
          dragmode=False  # Desactivar el modo de arrastre
      )
    #estableciendo una lista con los 10 paises con mayo produccion
    top_10 = data.nlargest(10, year)

    fig2 = px.bar(top_10,
                  x=year,
                  y='Paises',
                  color='Paises',
                  color_discrete_sequence=px.colors.qualitative.Prism,
                  title=f'10 paises con mayor consumo de energia en {year}')
    fig2.update_layout(showlegend=False)

    # aqui se arma el grafico de lineas de los 10 paises mostrados
    df_long = pd.melt(top_10, id_vars=['Paises'], var_name='Año', value_name='Mtoe')
    fig3 = px.line(df_long, x='Año', y='Mtoe', color='Paises', markers=True, log_y=True,
                title='Evolución de datos por país (1990-2023)')
    fig3.update_layout(
        yaxis=dict(
            showticklabels=False  # Ocultar etiquetas del eje y
        )
    )

    #aqui se mostrar el grafico del modelo predictivo
    datos_pais = cons_combinado.loc[data['Paises'] == pais].values[0]
    datos_valores = datos_pais[1:-3]
    datos_anio = np.arange(1990, 2024).astype(float)
    x = datos_anio.reshape(-1, 1)
    y = datos_valores.astype(float)

    coef = np.polyfit(datos_anio, y, 5)
    y_poly_pred = np.polyval(coef, datos_anio)
    prediccion = np.polyval(coef, f_year)



    # Crear trazas para el gráfico
    trace1 = go.Scatter(
          x=datos_anio,
          y=y,
          mode='lines+markers',
          name='Datos originales'
      )

    trace2 = go.Scatter(
          x=datos_anio,
          y=y_poly_pred,
          mode='lines',
          name='Modelo Polinómico',
          line=dict(color='green')
      )

    # Crear layout del gráfico
    layout = go.Layout(
          title=f'La predicción aproximada en Mtoe para el año {f_year} es de {prediccion} para {pais}.',
          xaxis=dict(title='Año', showgrid=True),
          yaxis=dict(title='Mtoe', showgrid=True),
          showlegend=True
      )

    # Crear figura con las trazas y el layout
    fig4 = go.Figure(data=[trace1, trace2], layout=layout)
    # Devolver las figura para que se actualice el gráfico
    return fig, fig2, fig3, fig4
  except Exception as e:
    print(f"Error al generar las figuras: {e}")
    return dash.no_update, dash.no_update, dash.no_update, dash.no_update


# Ejecutar la aplicación
if __name__ == '__main__':
    app.run_server(debug=True)

In [13]:
data = cons_combinado.copy()
top_10 = data.nlargest(10, 2015)
top_10.head(10)

,Paises,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2017,2018,2019,2020,2021,2022,2023,continent,iso_alpha,iso_num
24,China,741.823517,770.442323,798.355499,844.317145,887.615661,950.733426,993.738292,984.703139,935.508822,...,3112.928690,3253.080392,3395.561886,3499.707607,3719.264730,3808.522517,4059.945349,Asia,CHN,156
134,United States,1911.016994,1928.652956,1966.416214,1999.339908,2039.288619,2064.038185,2113.582190,2134.838507,2150.370626,...,2156.896887,2220.647293,2220.717580,2047.549098,2149.106623,2170.772928,2171.550747,Americas,USA,840
58,India,283.921198,296.985812,311.401023,318.325647,333.787657,350.003748,372.313358,385.674061,397.200386,...,945.572383,983.556673,988.105923,941.143944,1012.816650,1080.589545,1135.276687,Asia,IND,356
142,Rusia,888.726788,879.507617,805.111299,760.469062,663.242841,641.915379,637.461289,609.256470,594.567540,...,741.219305,801.853604,763.162913,759.301180,838.361748,836.314912,838.419847,Europe,RUS,643
66,Japan,438.241979,444.148682,455.284711,458.546331,483.914141,497.547563,508.189400,513.575741,504.470789,...,442.178710,435.934885,426.005411,396.772817,413.027771,404.638199,390.562546,Asia,JPN,392
14,Brazil,147.053362,150.514890,152.086269,156.196748,165.168415,169.601090,178.324433,188.737988,193.219796,...,309.162391,304.214026,309.550169,305.342898,323.631732,325.286473,336.102685,Americas,BRA,76
47,Germany,351.414103,344.605918,338.201135,334.892921,333.332617,336.846718,348.226135,345.200062,343.097176,...,311.394225,303.614035,296.903865,278.755069,288.654312,271.377740,246.244773,Europe,DEU,276
20,Canada,212.283682,211.751113,216.753660,223.820978,231.992956,235.339180,240.150303,242.631670,241.142604,...,302.718958,307.163224,309.540282,288.798620,295.132792,299.881958,297.160943,Americas,CAN,124
44,France,224.366808,237.292173,233.939390,237.671497,230.803814,239.682024,250.674893,244.129799,251.630866,...,247.556619,246.099336,242.597754,217.787582,233.818094,209.589094,212.070649,Europe,FRA,250
109,Saudi Arabia,63.654596,77.545709,89.079416,96.578416,97.011518,98.838279,98.087595,89.458252,94.400369,...,246.669322,254.012564,262.094442,248.926324,256.267744,280.034764,278.885464,Asia,SAU,682

In [14]:
data_ord = data.sort_values(by=2015)
data_ord.head(10)

,Paises,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2017,2018,2019,2020,2021,2022,2023,continent,iso_alpha,iso_num
34,Denmark,17.308076,19.206284,18.373981,18.902425,19.566518,19.615551,22.360343,20.855850,20.571658,...,16.699226,16.633717,16.030834,15.364187,16.165333,15.496544,15.119591,Europe,DNK,208
103,Portugal,16.795593,16.945571,18.062927,17.822688,18.238494,20.213772,20.034045,21.118505,22.834042,...,22.727374,21.988614,21.736459,20.128176,20.095292,20.317421,18.980211,Europe,PRT,620
91,New Zealand,14.104961,14.337723,14.777329,15.490717,15.473137,15.491357,15.898612,16.364121,16.233644,...,22.939422,22.317671,23.021242,22.221559,22.552877,21.920716,22.772330,Oceania,NZL,554
95,Norway,20.493984,21.001107,21.315755,22.682833,22.216863,22.515576,22.051122,23.220951,24.421560,...,29.791268,29.794152,28.299655,27.963947,28.962390,25.451355,23.287566,Europe,NOR,578
113,Singapore,16.254210,16.501605,17.532602,18.598659,22.026202,16.056046,18.525255,23.170497,19.297195,...,36.122977,33.224624,35.552630,35.630496,36.208420,43.754590,35.326487,Asia,SGP,702
106,Romania,62.012375,51.031378,46.040916,45.659734,43.089716,46.571280,47.800012,44.848884,41.035093,...,33.256411,33.502507,33.120139,32.252512,34.246073,31.617883,30.806060,Europe,ROU,642
71,Kuwait,14.008281,5.365732,11.168121,18.503931,20.563000,20.888893,19.360097,20.929991,19.761942,...,38.687591,39.605574,40.683962,37.192106,36.931520,40.230491,39.436367,Asia,KWT,414
23,Chile,13.776363,14.181269,15.363250,15.742346,16.948388,18.222471,20.152292,22.477959,23.350795,...,39.242019,40.017877,42.301985,38.376102,40.929261,42.274833,40.295341,Americas,CHL,152
25,Colombia,26.557000,28.293737,28.611407,29.594489,30.946038,30.291838,30.903922,32.130625,31.978214,...,39.250277,38.706679,42.610228,39.711274,41.906028,43.309708,45.348766,Americas,COL,170
122,Sweden,47.073605,48.581958,46.404677,46.318139,49.580179,50.184867,51.343544,50.009617,50.870643,...,48.818017,49.828694,48.578624,43.964210,46.885778,44.693535,45.639874,Europe,SWE,752

## Preguntas que se responden con este grafico

### ¿cuales son los paises con mayor consumo de energia electrica en un año determinado?

### ¿de los paises con mayor consumo en ese año especifico cual es su historial de consumo a lo largo de los años?

### **¿que informacion relevante me puede interesar al analizar este grafico?**
### este grafico puede ser de gran interes para una empresa que este interesada en el mercado energetico, ya que le proporciona valiosa informacion sobre potenciales clientes al rededor del mundo, asi tambien se tendra una idea aproximada de la ubicacion del pais, lo que permitira dependiendo de la fase de proyecto, hacer oportunos ajustes a la logistica de la planeacion del proyecto de inversion

###**¿que es Mtoe?**
### mega toneladas equivalentes de petróleo a megajulio (MJ)	41 867 999 409